### ISSUE TITLE
Proposal about folder structure

### ISSUE THREAD

**Issue by ranmerc** [Moeen-Ul-Islam/VIT-MCA-PAPERS#5]
Hello bhaiya, I really appreciate your effort here; it definitely helped us a lot this semester.

Now that our fall semester is over, I was thinking of contributing too. I have some suggestions regarding the folder structure.
I would like to propose the following structure to accommodate multiple semesters -

```
[MAT5007] Applied Statistical Methods
    /21FALL
    /22FALL
```

Do let me know what you think of it, and I will create a PR for this.

**Comment by MoeenKhalil** [comment]
Hi, glad it helped!
Sure please create a plan for it, would be great for upcoming students as well.
Rally appreciate your initiative.

**Comment by MoeenKhalil** [comment]
Can you please add the info in the readme file explaining the folder structure for the upcoming contributors?
